// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module moving_max_moving_max_Pipeline_MAIN_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        window_load_6,
        window_load_5,
        window_load_4,
        window_load_3,
        window_load_2,
        window_load_1,
        window_load,
        in_data_address0,
        in_data_ce0,
        in_data_q0,
        out_data_address0,
        out_data_ce0,
        out_data_we0,
        out_data_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] window_load_6;
input  [31:0] window_load_5;
input  [31:0] window_load_4;
input  [31:0] window_load_3;
input  [31:0] window_load_2;
input  [31:0] window_load_1;
input  [31:0] window_load;
output  [5:0] in_data_address0;
output   in_data_ce0;
input  [31:0] in_data_q0;
output  [5:0] out_data_address0;
output   out_data_ce0;
output   out_data_we0;
output  [31:0] out_data_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln17_fu_193_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln17_reg_413;
reg   [0:0] icmp_ln17_reg_413_pp0_iter1_reg;
reg   [0:0] icmp_ln17_reg_413_pp0_iter2_reg;
wire   [63:0] zext_ln17_fu_205_p1;
reg   [63:0] zext_ln17_reg_417;
reg   [63:0] zext_ln17_reg_417_pp0_iter1_reg;
reg   [63:0] zext_ln17_reg_417_pp0_iter2_reg;
reg   [63:0] zext_ln17_reg_417_pp0_iter3_reg;
reg   [31:0] max_value_19_reg_427;
wire   [31:0] max_value_18_fu_244_p3;
reg   [31:0] max_value_18_reg_434;
reg   [31:0] max_value_23_reg_440;
wire   [31:0] max_value_22_fu_289_p3;
reg   [31:0] max_value_22_reg_447;
reg   [31:0] max_value_25_reg_453;
wire   [31:0] max_value_26_fu_325_p3;
reg   [31:0] max_value_26_reg_458;
reg    ap_condition_exit_pp0_iter3_stage0;
wire    ap_block_pp0_stage0;
reg   [31:0] max_value_13_fu_50;
wire    ap_loop_init;
reg   [6:0] n_fu_54;
wire   [6:0] add_ln17_fu_199_p2;
reg   [6:0] ap_sig_allocacmp_n_1;
reg   [31:0] max_value_11_fu_58;
reg   [31:0] max_value_9_fu_62;
reg   [31:0] max_value_7_fu_66;
reg   [31:0] max_value_5_fu_70;
reg   [31:0] max_value_3_fu_74;
reg   [31:0] max_value_1_fu_78;
reg    in_data_ce0_local;
reg    out_data_we0_local;
wire   [31:0] max_value_27_fu_345_p3;
reg    out_data_ce0_local;
wire   [0:0] icmp_ln37_fu_224_p2;
wire   [31:0] max_value_16_fu_230_p3;
wire   [0:0] icmp_ln37_1_fu_238_p2;
wire   [0:0] icmp_ln37_2_fu_273_p2;
wire   [31:0] max_value_20_fu_277_p3;
wire   [0:0] icmp_ln37_3_fu_283_p2;
wire   [0:0] icmp_ln37_4_fu_309_p2;
wire   [31:0] max_value_24_fu_313_p3;
wire   [0:0] icmp_ln37_5_fu_319_p2;
wire   [0:0] icmp_ln37_6_fu_340_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 max_value_13_fu_50 = 32'd0;
#0 n_fu_54 = 7'd0;
#0 max_value_11_fu_58 = 32'd0;
#0 max_value_9_fu_62 = 32'd0;
#0 max_value_7_fu_66 = 32'd0;
#0 max_value_5_fu_70 = 32'd0;
#0 max_value_3_fu_74 = 32'd0;
#0 max_value_1_fu_78 = 32'd0;
#0 ap_done_reg = 1'b0;
end

moving_max_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter3_stage0)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_value_11_fu_58 <= window_load_1;
        end else if (((icmp_ln17_reg_413_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            max_value_11_fu_58 <= max_value_23_reg_440;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_value_13_fu_50 <= window_load;
        end else if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
            max_value_13_fu_50 <= max_value_25_reg_453;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_value_1_fu_78 <= window_load_6;
        end else if (((icmp_ln17_reg_413 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            max_value_1_fu_78 <= in_data_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_value_3_fu_74 <= window_load_5;
        end else if (((icmp_ln17_reg_413 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            max_value_3_fu_74 <= max_value_1_fu_78;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            max_value_5_fu_70 <= window_load_4;
        end else if (((icmp_ln17_reg_413 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            max_value_5_fu_70 <= max_value_3_fu_74;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_value_7_fu_66 <= window_load_3;
        end else if (((icmp_ln17_reg_413_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            max_value_7_fu_66 <= max_value_19_reg_427;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            max_value_9_fu_62 <= window_load_2;
        end else if (((icmp_ln17_reg_413_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            max_value_9_fu_62 <= max_value_7_fu_66;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln17_fu_193_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_54 <= add_ln17_fu_199_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_54 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln17_reg_413 <= icmp_ln17_fu_193_p2;
        icmp_ln17_reg_413_pp0_iter1_reg <= icmp_ln17_reg_413;
        max_value_18_reg_434 <= max_value_18_fu_244_p3;
        max_value_19_reg_427 <= max_value_5_fu_70;
        zext_ln17_reg_417[6 : 0] <= zext_ln17_fu_205_p1[6 : 0];
        zext_ln17_reg_417_pp0_iter1_reg[6 : 0] <= zext_ln17_reg_417[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln17_reg_413_pp0_iter2_reg <= icmp_ln17_reg_413_pp0_iter1_reg;
        max_value_22_reg_447 <= max_value_22_fu_289_p3;
        max_value_23_reg_440 <= max_value_9_fu_62;
        max_value_25_reg_453 <= max_value_11_fu_58;
        max_value_26_reg_458 <= max_value_26_fu_325_p3;
        zext_ln17_reg_417_pp0_iter2_reg[6 : 0] <= zext_ln17_reg_417_pp0_iter1_reg[6 : 0];
        zext_ln17_reg_417_pp0_iter3_reg[6 : 0] <= zext_ln17_reg_417_pp0_iter2_reg[6 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln17_fu_193_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln17_reg_413_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_ce0_local = 1'b1;
    end else begin
        in_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_data_ce0_local = 1'b1;
    end else begin
        out_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_data_we0_local = 1'b1;
    end else begin
        out_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_fu_199_p2 = (ap_sig_allocacmp_n_1 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln17_fu_193_p2 = ((ap_sig_allocacmp_n_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln37_1_fu_238_p2 = (($signed(max_value_3_fu_74) > $signed(max_value_16_fu_230_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_2_fu_273_p2 = (($signed(max_value_19_reg_427) > $signed(max_value_18_reg_434)) ? 1'b1 : 1'b0);

assign icmp_ln37_3_fu_283_p2 = (($signed(max_value_7_fu_66) > $signed(max_value_20_fu_277_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_4_fu_309_p2 = (($signed(max_value_23_reg_440) > $signed(max_value_22_reg_447)) ? 1'b1 : 1'b0);

assign icmp_ln37_5_fu_319_p2 = (($signed(max_value_11_fu_58) > $signed(max_value_24_fu_313_p3)) ? 1'b1 : 1'b0);

assign icmp_ln37_6_fu_340_p2 = (($signed(max_value_13_fu_50) > $signed(max_value_26_reg_458)) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_224_p2 = (($signed(max_value_1_fu_78) > $signed(in_data_q0)) ? 1'b1 : 1'b0);

assign in_data_address0 = zext_ln17_fu_205_p1;

assign in_data_ce0 = in_data_ce0_local;

assign max_value_16_fu_230_p3 = ((icmp_ln37_fu_224_p2[0:0] == 1'b1) ? max_value_1_fu_78 : in_data_q0);

assign max_value_18_fu_244_p3 = ((icmp_ln37_1_fu_238_p2[0:0] == 1'b1) ? max_value_3_fu_74 : max_value_16_fu_230_p3);

assign max_value_20_fu_277_p3 = ((icmp_ln37_2_fu_273_p2[0:0] == 1'b1) ? max_value_19_reg_427 : max_value_18_reg_434);

assign max_value_22_fu_289_p3 = ((icmp_ln37_3_fu_283_p2[0:0] == 1'b1) ? max_value_7_fu_66 : max_value_20_fu_277_p3);

assign max_value_24_fu_313_p3 = ((icmp_ln37_4_fu_309_p2[0:0] == 1'b1) ? max_value_23_reg_440 : max_value_22_reg_447);

assign max_value_26_fu_325_p3 = ((icmp_ln37_5_fu_319_p2[0:0] == 1'b1) ? max_value_11_fu_58 : max_value_24_fu_313_p3);

assign max_value_27_fu_345_p3 = ((icmp_ln37_6_fu_340_p2[0:0] == 1'b1) ? max_value_13_fu_50 : max_value_26_reg_458);

assign out_data_address0 = zext_ln17_reg_417_pp0_iter3_reg;

assign out_data_ce0 = out_data_ce0_local;

assign out_data_d0 = max_value_27_fu_345_p3;

assign out_data_we0 = out_data_we0_local;

assign zext_ln17_fu_205_p1 = ap_sig_allocacmp_n_1;

always @ (posedge ap_clk) begin
    zext_ln17_reg_417[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln17_reg_417_pp0_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln17_reg_417_pp0_iter2_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    zext_ln17_reg_417_pp0_iter3_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //moving_max_moving_max_Pipeline_MAIN_LOOP
