domain_path: C:/Users/nocl1p/Projects/rd_hw/hw4/zynq_ps/vitis/zynq_platform/export/zynq_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: C:\AMDDesignTools\2026.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
