domain_path: C:/Users/nocl1p/Projects/rd_hw/hw5/vitis/hw5_platform/export/hw5_platform/sw/standalone_microblaze_0
app_src_dir: C:\AMDDesignTools\2026.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
