-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity moving_max_moving_max_Pipeline_MAIN_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    window_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_load : IN STD_LOGIC_VECTOR (31 downto 0);
    in_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    in_data_ce0 : OUT STD_LOGIC;
    in_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    out_data_ce0 : OUT STD_LOGIC;
    out_data_we0 : OUT STD_LOGIC;
    out_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of moving_max_moving_max_Pipeline_MAIN_LOOP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln17_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln17_reg_413 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_413_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_413_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln17_fu_205_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln17_reg_417 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln17_reg_417_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln17_reg_417_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln17_reg_417_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal max_value_19_reg_427 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_18_fu_244_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_18_reg_434 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_23_reg_440 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_22_fu_289_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_22_reg_447 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_25_reg_453 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_26_fu_325_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_value_26_reg_458 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal max_value_13_fu_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal n_fu_54 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln17_fu_199_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_n_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal max_value_11_fu_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_value_9_fu_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_value_7_fu_66 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_value_5_fu_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_value_3_fu_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal max_value_1_fu_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_data_ce0_local : STD_LOGIC;
    signal out_data_we0_local : STD_LOGIC;
    signal max_value_27_fu_345_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_data_ce0_local : STD_LOGIC;
    signal icmp_ln37_fu_224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_value_16_fu_230_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln37_1_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_2_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_value_20_fu_277_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln37_3_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_4_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max_value_24_fu_313_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln37_5_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_6_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component moving_max_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component moving_max_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    max_value_11_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    max_value_11_fu_58 <= window_load_1;
                elsif (((icmp_ln17_reg_413_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    max_value_11_fu_58 <= max_value_23_reg_440;
                end if;
            end if; 
        end if;
    end process;

    max_value_13_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    max_value_13_fu_50 <= window_load;
                elsif ((ap_enable_reg_pp0_iter4 = ap_const_logic_1)) then 
                    max_value_13_fu_50 <= max_value_25_reg_453;
                end if;
            end if; 
        end if;
    end process;

    max_value_1_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    max_value_1_fu_78 <= window_load_6;
                elsif (((icmp_ln17_reg_413 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    max_value_1_fu_78 <= in_data_q0;
                end if;
            end if; 
        end if;
    end process;

    max_value_3_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    max_value_3_fu_74 <= window_load_5;
                elsif (((icmp_ln17_reg_413 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    max_value_3_fu_74 <= max_value_1_fu_78;
                end if;
            end if; 
        end if;
    end process;

    max_value_5_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    max_value_5_fu_70 <= window_load_4;
                elsif (((icmp_ln17_reg_413 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    max_value_5_fu_70 <= max_value_3_fu_74;
                end if;
            end if; 
        end if;
    end process;

    max_value_7_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    max_value_7_fu_66 <= window_load_3;
                elsif (((icmp_ln17_reg_413_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    max_value_7_fu_66 <= max_value_19_reg_427;
                end if;
            end if; 
        end if;
    end process;

    max_value_9_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    max_value_9_fu_62 <= window_load_2;
                elsif (((icmp_ln17_reg_413_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    max_value_9_fu_62 <= max_value_7_fu_66;
                end if;
            end if; 
        end if;
    end process;

    n_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln17_fu_193_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n_fu_54 <= add_ln17_fu_199_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n_fu_54 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln17_reg_413 <= icmp_ln17_fu_193_p2;
                icmp_ln17_reg_413_pp0_iter1_reg <= icmp_ln17_reg_413;
                max_value_18_reg_434 <= max_value_18_fu_244_p3;
                max_value_19_reg_427 <= max_value_5_fu_70;
                    zext_ln17_reg_417(6 downto 0) <= zext_ln17_fu_205_p1(6 downto 0);
                    zext_ln17_reg_417_pp0_iter1_reg(6 downto 0) <= zext_ln17_reg_417(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln17_reg_413_pp0_iter2_reg <= icmp_ln17_reg_413_pp0_iter1_reg;
                max_value_22_reg_447 <= max_value_22_fu_289_p3;
                max_value_23_reg_440 <= max_value_9_fu_62;
                max_value_25_reg_453 <= max_value_11_fu_58;
                max_value_26_reg_458 <= max_value_26_fu_325_p3;
                    zext_ln17_reg_417_pp0_iter2_reg(6 downto 0) <= zext_ln17_reg_417_pp0_iter1_reg(6 downto 0);
                    zext_ln17_reg_417_pp0_iter3_reg(6 downto 0) <= zext_ln17_reg_417_pp0_iter2_reg(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln17_reg_417(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    zext_ln17_reg_417_pp0_iter1_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    zext_ln17_reg_417_pp0_iter2_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    zext_ln17_reg_417_pp0_iter3_reg(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln17_fu_199_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n_1) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln17_fu_193_p2)
    begin
        if (((icmp_ln17_fu_193_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, icmp_ln17_reg_413_pp0_iter2_reg)
    begin
        if (((icmp_ln17_reg_413_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, n_fu_54)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_n_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_n_1 <= n_fu_54;
        end if; 
    end process;

    icmp_ln17_fu_193_p2 <= "1" when (ap_sig_allocacmp_n_1 = ap_const_lv7_40) else "0";
    icmp_ln37_1_fu_238_p2 <= "1" when (signed(max_value_3_fu_74) > signed(max_value_16_fu_230_p3)) else "0";
    icmp_ln37_2_fu_273_p2 <= "1" when (signed(max_value_19_reg_427) > signed(max_value_18_reg_434)) else "0";
    icmp_ln37_3_fu_283_p2 <= "1" when (signed(max_value_7_fu_66) > signed(max_value_20_fu_277_p3)) else "0";
    icmp_ln37_4_fu_309_p2 <= "1" when (signed(max_value_23_reg_440) > signed(max_value_22_reg_447)) else "0";
    icmp_ln37_5_fu_319_p2 <= "1" when (signed(max_value_11_fu_58) > signed(max_value_24_fu_313_p3)) else "0";
    icmp_ln37_6_fu_340_p2 <= "1" when (signed(max_value_13_fu_50) > signed(max_value_26_reg_458)) else "0";
    icmp_ln37_fu_224_p2 <= "1" when (signed(max_value_1_fu_78) > signed(in_data_q0)) else "0";
    in_data_address0 <= zext_ln17_fu_205_p1(6 - 1 downto 0);
    in_data_ce0 <= in_data_ce0_local;

    in_data_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_data_ce0_local <= ap_const_logic_1;
        else 
            in_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    max_value_16_fu_230_p3 <= 
        max_value_1_fu_78 when (icmp_ln37_fu_224_p2(0) = '1') else 
        in_data_q0;
    max_value_18_fu_244_p3 <= 
        max_value_3_fu_74 when (icmp_ln37_1_fu_238_p2(0) = '1') else 
        max_value_16_fu_230_p3;
    max_value_20_fu_277_p3 <= 
        max_value_19_reg_427 when (icmp_ln37_2_fu_273_p2(0) = '1') else 
        max_value_18_reg_434;
    max_value_22_fu_289_p3 <= 
        max_value_7_fu_66 when (icmp_ln37_3_fu_283_p2(0) = '1') else 
        max_value_20_fu_277_p3;
    max_value_24_fu_313_p3 <= 
        max_value_23_reg_440 when (icmp_ln37_4_fu_309_p2(0) = '1') else 
        max_value_22_reg_447;
    max_value_26_fu_325_p3 <= 
        max_value_11_fu_58 when (icmp_ln37_5_fu_319_p2(0) = '1') else 
        max_value_24_fu_313_p3;
    max_value_27_fu_345_p3 <= 
        max_value_13_fu_50 when (icmp_ln37_6_fu_340_p2(0) = '1') else 
        max_value_26_reg_458;
    out_data_address0 <= zext_ln17_reg_417_pp0_iter3_reg(6 - 1 downto 0);
    out_data_ce0 <= out_data_ce0_local;

    out_data_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_data_ce0_local <= ap_const_logic_1;
        else 
            out_data_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_data_d0 <= max_value_27_fu_345_p3;
    out_data_we0 <= out_data_we0_local;

    out_data_we0_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_data_we0_local <= ap_const_logic_1;
        else 
            out_data_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln17_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_n_1),64));
end behav;
