-- ==============================================================
-- Generated by Vitis HLS v2026.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity moving_max is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    in_data_ce0 : OUT STD_LOGIC;
    in_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    out_data_ce0 : OUT STD_LOGIC;
    out_data_we0 : OUT STD_LOGIC;
    out_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of moving_max is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "moving_max_moving_max,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.500000,HLS_SYN_LAT=79,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=576,HLS_SYN_LUT=746,HLS_VERSION=2026_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_idle : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_ready : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_ce0 : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_ce0 : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_we0 : STD_LOGIC;
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln10_fu_74_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal k_fu_40 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln10_fu_80_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component moving_max_moving_max_Pipeline_MAIN_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load : IN STD_LOGIC_VECTOR (31 downto 0);
        in_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        in_data_ce0 : OUT STD_LOGIC;
        in_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_data_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        out_data_ce0 : OUT STD_LOGIC;
        out_data_we0 : OUT STD_LOGIC;
        out_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_moving_max_Pipeline_MAIN_LOOP_fu_44 : component moving_max_moving_max_Pipeline_MAIN_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start,
        ap_done => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done,
        ap_idle => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_idle,
        ap_ready => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_ready,
        window_load_6 => ap_const_lv32_80000000,
        window_load_5 => ap_const_lv32_80000000,
        window_load_4 => ap_const_lv32_80000000,
        window_load_3 => ap_const_lv32_80000000,
        window_load_2 => ap_const_lv32_80000000,
        window_load_1 => ap_const_lv32_80000000,
        window_load => ap_const_lv32_80000000,
        in_data_address0 => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_address0,
        in_data_ce0 => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_ce0,
        in_data_q0 => in_data_q0,
        out_data_address0 => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_address0,
        out_data_ce0 => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_ce0,
        out_data_we0 => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_we0,
        out_data_d0 => grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln10_fu_74_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_ready = ap_const_logic_1)) then 
                    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_fu_40_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                k_fu_40 <= ap_const_lv4_0;
            elsif (((icmp_ln10_fu_74_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                k_fu_40 <= add_ln10_fu_80_p2;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done, ap_CS_fsm_state2, icmp_ln10_fu_74_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln10_fu_74_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln10_fu_80_p2 <= std_logic_vector(unsigned(k_fu_40) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done)
    begin
        if ((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg;
    icmp_ln10_fu_74_p2 <= "1" when (k_fu_40 = ap_const_lv4_8) else "0";
    in_data_address0 <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_address0;
    in_data_ce0 <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_ce0;
    out_data_address0 <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_address0;
    out_data_ce0 <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_ce0;
    out_data_d0 <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_d0;
    out_data_we0 <= grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_we0;
end behav;
