// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="moving_max_moving_max,hls_ip_2026_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.500000,HLS_SYN_LAT=79,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=576,HLS_SYN_LUT=746,HLS_VERSION=2026_1}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module moving_max (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_data_address0,
        in_data_ce0,
        in_data_q0,
        out_data_address0,
        out_data_ce0,
        out_data_we0,
        out_data_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] in_data_address0;
output   in_data_ce0;
input  [31:0] in_data_q0;
output  [5:0] out_data_address0;
output   out_data_ce0;
output   out_data_we0;
output  [31:0] out_data_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_idle;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_ready;
wire   [5:0] grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_address0;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_ce0;
wire   [5:0] grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_address0;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_ce0;
wire    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_we0;
wire   [31:0] grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_d0;
reg    grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln10_fu_74_p2;
wire    ap_CS_fsm_state3;
reg   [3:0] k_fu_40;
wire   [3:0] add_ln10_fu_80_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg = 1'b0;
#0 k_fu_40 = 4'd0;
end

moving_max_moving_max_Pipeline_MAIN_LOOP grp_moving_max_Pipeline_MAIN_LOOP_fu_44(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start),
    .ap_done(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done),
    .ap_idle(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_idle),
    .ap_ready(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_ready),
    .window_load_6(32'd2147483648),
    .window_load_5(32'd2147483648),
    .window_load_4(32'd2147483648),
    .window_load_3(32'd2147483648),
    .window_load_2(32'd2147483648),
    .window_load_1(32'd2147483648),
    .window_load(32'd2147483648),
    .in_data_address0(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_address0),
    .in_data_ce0(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_ce0),
    .in_data_q0(in_data_q0),
    .out_data_address0(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_address0),
    .out_data_ce0(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_ce0),
    .out_data_we0(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_we0),
    .out_data_d0(grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln10_fu_74_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg <= 1'b1;
        end else if ((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_ready == 1'b1)) begin
            grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_fu_40 <= 4'd0;
    end else if (((icmp_ln10_fu_74_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        k_fu_40 <= add_ln10_fu_80_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln10_fu_74_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_80_p2 = (k_fu_40 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_ap_start_reg;

assign icmp_ln10_fu_74_p2 = ((k_fu_40 == 4'd8) ? 1'b1 : 1'b0);

assign in_data_address0 = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_address0;

assign in_data_ce0 = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_in_data_ce0;

assign out_data_address0 = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_address0;

assign out_data_ce0 = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_ce0;

assign out_data_d0 = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_d0;

assign out_data_we0 = grp_moving_max_Pipeline_MAIN_LOOP_fu_44_out_data_we0;

endmodule //moving_max
